keys:
  - &framework-13 age14dnfyq56r7exkjx58gs4s8xlhn6sd05l3aufr540r374ca7mcf6qdv0yhw
  - &srv-prod-2 age1auwa57jefln7sfelfx8l3sfacpwt3t2fxqch8643jyht7mtjwqzq8yxjzq
  - &srv-prod-3 age1nhvr8nmagdwjmp488edhh5zm9relctnue5mvqwrxynkzydl0aqqshzvy7w
  - &srv-prod-4 age1yyf88xrxwjj83a8kapuxkvsf8pmu4qasaul5ttjkzve4evx8dq0swl89gy
  - &srv-offsite-1 age1qy4nn0tr7mlkhwkc77vshnpuknsnvgu5y4jwfkmmazfd38acspkscslsc3
  - &directions age1tqwmx8ge4fxkj2l8sfam94eg52km2w3dqjgazjez46m4ywln7qls0unsdw
creation_rules:
  - path_regex: systems/host-keys\.yaml$
    key_groups:
      - age:
          - *framework-13
  - path_regex: systems/x86_64-linux/srv-prod-2/secrets\.yaml$
    key_groups:
      - age:
          - *framework-13
          - *srv-prod-2
  - path_regex: systems/x86_64-linux/srv-prod-3/secrets\.yaml$
    key_groups:
      - age:
          - *framework-13
          - *srv-prod-3
  - path_regex: systems/x86_64-linux/srv-prod-4/secrets\.yaml$
    key_groups:
      - age:
          - *framework-13
          - *srv-prod-4
  - path_regex: systems/x86_64-linux/srv-offsite-1/secrets\.yaml$
    key_groups:
      - age:
          - *framework-13
          - *srv-offsite-1
  - path_regex: systems/aarch64-linux/directions/secrets\.yaml$
    key_groups:
      - age:
          - *framework-13
          - *directions
