name: "CI Build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-system:
    name: Build system
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - configuration: framework-13
            runner: ubuntu-latest
          - configuration: srv-prod-2
            runner: ubuntu-latest
          - configuration: srv-prod-3
            runner: ubuntu-latest
          - configuration: srv-prod-4
            runner: ubuntu-latest
          - configuration: srv-prod-5
            runner: ubuntu-latest
          - configuration: srv-offsite-1
            runner: ubuntu-latest
          - configuration: directions
            runner: ubuntu-24.04-arm
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@1d87d45818068401a10cf16bdc5f00b24994a83f # main
      - run: nix build .#nixosConfigurations.${{ matrix.configuration }}.config.system.build.toplevel
  build-iso:
    name: Build ISOs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@1d87d45818068401a10cf16bdc5f00b24994a83f # main
      - run: nix build .#nixosConfigurations.minimal-server-iso.config.system.build.isoImage
  build-home-manager:
    name: Build standalone home-manager config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          [
            "benedikt",
            "bene",
          ]
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@1d87d45818068401a10cf16bdc5f00b24994a83f # main
      - run: nix build .#homeConfigurations.${{ matrix.configuration }}.activationPackage
