name: "CI Build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-system:
    name: Build system
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - configuration: framework-13
            runner: ubuntu-latest
          - configuration: srv-prod-1
            runner: ubuntu-latest
          - configuration: srv-prod-2
            runner: ubuntu-latest
          - configuration: srv-prod-3
            runner: ubuntu-latest
          - configuration: srv-prod-4
            runner: ubuntu-latest
          - configuration: srv-prod-5
            runner: ubuntu-latest
          - configuration: srv-prod-6
            runner: ubuntu-latest
          - configuration: srv-offsite-1
            runner: ubuntu-latest
          - configuration: directions
            runner: ubuntu-24.04-arm
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: DeterminateSystems/nix-installer-action@a7ad9c4f0c65208097f4d34f3cfa1913b80cce5c # main
        with:
          extra-conf: |
            extra-substituters = https://noctalia.cachix.org
            extra-trusted-public-keys = noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4=
      - run: nix build .#nixosConfigurations.${{ matrix.configuration }}.config.system.build.toplevel
  build-iso:
    name: Build ISOs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: DeterminateSystems/nix-installer-action@a7ad9c4f0c65208097f4d34f3cfa1913b80cce5c # main
        with:
          extra-conf: |
            extra-substituters = https://noctalia.cachix.org
            extra-trusted-public-keys = noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4=
      - run: nix build .#nixosConfigurations.minimal-server-iso.config.system.build.isoImage
  build-home-manager:
    name: Build standalone home-manager config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ["benedikt", "bene"]
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: DeterminateSystems/nix-installer-action@a7ad9c4f0c65208097f4d34f3cfa1913b80cce5c # main
        with:
          extra-conf: |
            extra-substituters = https://noctalia.cachix.org
            extra-trusted-public-keys = noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4=
      - run: nix build .#homeConfigurations.${{ matrix.configuration }}.activationPackage
