name: "CI Build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-x86:
    name: Build x86 systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          ["framework-13", "srv-prod-2", "srv-prod-3", "srv-offsite-1"]
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@490cfee336d5220c80b0c5cab117b4a26fb3898a # main
      - run: nix build .#nixosConfigurations.${{ matrix.configuration }}.config.system.build.toplevel
  build-iso:
    name: Build ISOs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@490cfee336d5220c80b0c5cab117b4a26fb3898a # main
      - run: nix build .#nixosConfigurations.minimal-server-iso.config.system.build.isoImage
